spring:
  application:
    name: currency-exchange-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: zone_8761
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    
management:
  endpoints:
    web:
      exposure: 
        include: "*"
  server:
    port: 9091
   
    
hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 3000
    
server:
  port: 8000